### ISSUE TITLE
Inviting users to a company - or inviting them to the platform

### ISSUE THREAD

**Issue by viktorsmari** [fablabbcn/makeworks#14]
We can **not** allow to search by email, because than any user can see everyone's email address, which is a privacy issue.

#### TODO:
- [ ] In the select2 box, remove the email address - Or is it OK if it's only admins using it?
- [ ] In the select2 box, show users profile picture to help identify a user.
- [x] If admin, allow to search by email, else it's name only

2 scenarios when trying to invite an User (employee) to a company:
- User already has an account on MW
  - Company owners can search ALL USERS by name (not email) and give them access to their company.
  - We can allow only `superadmins` to search by name **and** email (because of privacy issues)
- User does not have an account on MW
  - We could create an account for him and invite using https://github.com/scambra/devise_invitable
  - The account will be created and the user will receive an email to confirm.
  - What if the user does not want an account? 
  - Maybe it is better if a user first creates an account on MW, then someone can invite him to the company.

## Examples - How GitHub invites users to repos
- If a user has an account on GitHub, we can easily find them by **name**.
- We cannot see any emails. If you type in a whole email address, you can send an email to invite the person.

![2021-04-22_13-37-30](https://user-images.githubusercontent.com/1689020/115708201-fb6f3a00-a36f-11eb-9a4c-e08770774748.png)
